name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        poetry-version: [1.1.4]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: install libsndfile1 on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libsndfile1
      - name: run tests
        run: |
          make test-data-download-source
          make test-data-download-generated-ci
          poetry install
          poetry run python ./tests/scripts/fix_prep_csv_paths.py
          poetry run pytest --models teenytweetynet  --cov=./ --cov-report=xml
